### ISSUE TITLE
Free please

### ISSUE THREAD

**Issue by scriptxd** [dev-bot-team/Tiktok-Live-View-Bot#1]
😮‍💨

**Comment by dev-bot-team** [comment]
Bro something I can give for free but I have to live from something too, the codes like this making money so if I give free what I earn? you sell tiktok services and earn money from free software? Common support development always by donating or paying stuff else developers will lose appetite and stop updating those codes which is not funny at all and extremally hard to make them work.

**Comment by scriptxd** [comment]
Hmmm...Understand... ❤️

**Comment by scriptxd** [comment]
Bro can u help on this...?

OSError: dlopen failed: library 👉 "libpthread.so.0" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/site-packages/tls_client/dependencies/tls-client-arm64.so in namespace (default)

Solution please

Tried Termux non root & Ubuntu Same Problem...

Installed  package : tls_client, sudo apt-get install libpthread-stubs0-dev

**Comment by dev-bot-team** [comment]
> Bro can u help on this...?
> 
> OSError: dlopen failed: library 👉 "libpthread.so.0" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/site-packages/tls_client/dependencies/tls-client-arm64.so in namespace (default)
> 
> Solution please
> 
> Tried Termux non root & Ubuntu Same Problem...
> 
> Installed package : tls_client, sudo apt-get install libpthread-stubs0-dev
> 
> Still missing libthread...
> 
> Latest Python and all package updated
> 
> Thanks In Advance ❤️

the Tiktok code is NOT FULL CODE it is only demonstration please check my telegram and lets talk if you wish you can buy it

**Comment by denzelxrt** [comment]
why tf would anyone buy this from you, this obiviously skidded and the fact your name is 'dev-bot-team'. grow up lmao
